### ISSUE TITLE
Persistent websockets

### ISSUE THREAD

**Issue by BRUHItsABunny** [sjfricke/Android-NDK-WebSocket#1]
Hey I am wondering if it's possible to use this library to achieve some sort of persistent connectivity throughout multiple JNI calls

Is it possible?

**Comment by sjfricke** [comment]
So the idea is when you create an instance of `WebSocket` it gets everything ready to use. 

When using the whole Java -> C++ flow you actually are calling [system.loadLibrary()](https://developer.android.com/training/articles/perf-jni#native-libraries) which loads in the .so file containing all the C++ code. This means if you have a `static` instance of WebSocket then when `system.loadLibrary()` is called the `WebSocket::WebSocket()` constructor gets kicked off and the memory is shared among every future JNI call to it

Hope that makes sense

**Comment by BRUHItsABunny** [comment]
i see, thank you that does make sense and I will try that

Can I link you to a repository if things don't work out?

**Comment by sjfricke** [comment]
Sure, I will try to find some time to look at it, for now going to close the comment, but feel free to send link in this issue still
