### ISSUE TITLE
Is the server-side supposed to work on Android or does it require a desktop Linux?

### ISSUE THREAD

**Issue by mavavilj** [sjfricke/Android-NDK-WebSocket#2]
Is the server-side supposed to work on Android or does it require a desktop Linux?

**Comment by mavavilj** [comment]
Particularly,

Is https://github.com/sjfricke/Android-NDK-WebSocket/blob/master/server/server.c essentially a web server with POSIX sockets or does it have more to it? Sorry, new to POSIX.

**Comment by sjfricke** [comment]
Android is a fork of Linux, it is POSIX compliant... Starting a server on Android is not a problem, essentially a localhost instance

**Comment by mavavilj** [comment]
Yes, but does this code work as it is?

**Comment by sjfricke** [comment]
Sorry, I guess I misread your original concern... So when I originally made this, I did have the server code run on a Linux machine connected to the same local WiFi as my Android device

**Comment by mavavilj** [comment]
Also,

If the code is POSIX-compliant, then it should run on all suitable POSIX-systems too. Right?

**Comment by sjfricke** [comment]
Yes, to my knowledge

**Comment by mavavilj** [comment]
Yes, but is it standard POSIX?

**Comment by sjfricke** [comment]
Sorry, I'm not an expert on POSIX

**Comment by Ezriral** [comment]
uselss
